"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, Play, ShieldCheck, Zap } from "lucide-react";
import type { BitgetStatus, Decision, Metrics } from "@/lib/types";

const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const pct=(n:number)=>(n*100).toFixed(1)+"%";
export function DashboardClient({ autoRun=false }:{autoRun?:boolean}) {
  const [data,setData]=useState<Metrics|null>(null); const [bitget,setBitget]=useState<BitgetStatus|null>(null); const [busy,setBusy]=useState(false); const [toast,setToast]=useState("");
  const load=useCallback(()=>fetch("/api/metrics",{cache:"no-store"}).then(r=>r.json()).then(setData),[]);
  const run=useCallback(async(scenario:"auto"|"safe"|"dangerous"="auto",batch=false)=>{setBusy(true);try{const r=await fetch(batch?"/api/agent/run-batch":"/api/agent/run-cycle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(batch?{count:10}:{scenario})});const result=await r.json();if(!r.ok)throw new Error(result.error||"Agent cycle failed");const d:Decision=batch?result.at(-1):result;setToast(batch?"10 Bitget mainnet paper cycles recorded":`${d.symbol} ${d.riskVerdict}: paper risk ${d.riskScore}/100`);await load()}catch(error){setToast(error instanceof Error?error.message:"Agent cycle failed")}finally{setBusy(false);setTimeout(()=>setToast(""),5000)}},[load]);
  useEffect(()=>{load();fetch("/api/bitget/status",{cache:"no-store"}).then(r=>r.json()).then(setBitget);if(autoRun)run("safe")},[autoRun,load,run]);
  if(!data)return <div className="empty">Loading risk control plane...</div>;
  const metrics=[["Total decisions",data.total,"Recorded"],["Approved",data.approved,"Passed controls"],["Blocked",data.blocked,"Unsafe actions stopped"],["Reduced",data.reduced,"Exposure constrained"],["Paper portfolio",money(data.portfolioValue),"Virtual balance"],["Paper PnL",money(data.pnl),"Cumulative"],["Win rate",pct(data.winRate),"Paper trades"],["Max drawdown",pct(data.maxDrawdown),"Peak to trough"]];
  return <><div className="topline"><div><span className="eyebrow">Control plane</span><h1>Agent operations</h1><span className="muted">Regime: {data.currentRegime.replaceAll("_"," ")} · Avg risk {data.averageRisk.toFixed(0)}/100</span><div style={{marginTop:10}}><span className={`status ${bitget?.publicMarketConnected?"":"BLOCK"}`}><i className="dot"/>{bitget?.publicMarketConnected?"Bitget mainnet data · paper only":"Bitget mainnet unavailable"}</span>{bitget?.btcPrice&&<span className="muted" style={{marginLeft:10}}>BTC {money(bitget.btcPrice)}</span>}</div></div><div className="actions"><button disabled={busy} className="btn btn-primary" onClick={()=>run("auto")}><Play size={14}/>Run mainnet paper cycle</button><button disabled={busy} className="btn" onClick={()=>run("auto",true)}><Zap size={14}/>Run 10 paper cycles</button><button disabled={busy} className="btn btn-danger" onClick={()=>run("dangerous")}><AlertTriangle size={14}/>Stress test</button></div></div>
  <div className="metrics">{metrics.map(([l,v,s])=><div className="card metric" key={l as string}><span>{l as string}</span><strong className={l==="Paper PnL"?(data.pnl>=0?"positive":"negative"):""}>{v as string|number}</strong><small>{s as string}</small></div>)}</div>
  <div className="layout2"><div className="card"><div className="card-title"><h3>Portfolio flight path</h3><span className="muted">Mainnet-priced paper ledger</span></div><div className="chart"><ResponsiveContainer><AreaChart data={data.equityCurve}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#35e6ad" stopOpacity={.35}/><stop offset="100%" stopColor="#35e6ad" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#ffffff0a" vertical={false}/><XAxis dataKey="timestamp" hide/><YAxis hide domain={["dataMin - 100","dataMax + 100"]}/><Tooltip contentStyle={{background:"#0b1018",border:"1px solid #ffffff18",fontSize:11}}/><Area dataKey="value" stroke="#35e6ad" fill="url(#g)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>
  <div className="card"><div className="card-title"><h3>Risk pulse</h3><ShieldCheck size={15} color="#35e6ad"/></div><div className="timeline">{data.decisions.slice(0,5).map(d=><div className="event" key={d.id}><b>{d.symbol} · <span className={d.riskVerdict}>{d.riskVerdict}</span></b><p>{d.riskReasons[0]||"All controls passed."}</p></div>)}{!data.decisions.length&&<div className="empty">Run a cycle to begin recording.</div>}</div></div></div>
  <div className="card" style={{marginTop:12}}><div className="card-title"><h3>Recent agent decisions</h3><Link href="/audit" className="muted">View full audit →</Link></div><DecisionTable decisions={data.decisions.slice(0,8)}/></div>
  {toast&&<div className="toast">{toast}</div>}</>;
}
export function DecisionTable({decisions}:{decisions:Decision[]}){return <div className="table-wrap"><table className="table"><thead><tr><th>Time</th><th>Agent / action</th><th>Signals</th><th>Regime</th><th>Risk</th><th>Mode</th><th>Verdict</th><th>Outcome</th></tr></thead><tbody>{decisions.map(d=><tr key={d.id}><td>{new Date(d.timestamp).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</td><td><Link href={`/decisions/${d.id}`}><b>{d.symbol} {d.side}</b><br/><span className="muted">{d.agentName}</span></Link></td><td><span className="signal-line">{d.signals.map((s,i)=><i key={i} title={s.category} className={`signal-dot ${s.score>.2?"safe":s.score<-.2?"danger":"neutral"}`}/>)}</span></td><td>{d.marketRegime.replaceAll("_"," ")}</td><td><span className={`risknum ${d.riskScore>60?"high":d.riskScore>30?"med":""}`}>{d.riskScore}</span>/100</td><td><span className="status">{d.executionMode}</span></td><td><span className={`pill ${d.riskVerdict}`}>{d.riskVerdict}</span></td><td className={d.resultPnL>=0?"positive":"negative"}>{money(d.resultPnL)}</td></tr>)}</tbody></table>{!decisions.length&&<div className="empty">No decisions match this view.</div>}</div>}
