import Link from "next/link";
import { notFound } from "next/navigation";
import { getDecision } from "@/lib/db/store";
export const dynamic="force-dynamic";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
export default async function DecisionPage({params}:{params:Promise<{id:string}>}){
  const d=await getDecision((await params).id);if(!d)notFound();
  return <main className="appmain"><div className="container"><div className="topline"><div><Link href="/audit" className="muted">← Audit trail</Link><h1>{d.symbol} {d.side}</h1><span className={`pill ${d.riskVerdict}`}>{d.riskVerdict}</span> <span className="muted">Risk {d.riskScore}/100 · {new Date(d.timestamp).toLocaleString()}</span></div></div>
  <div className="detail-grid"><div className="stack"><div className="card"><div className="card-title"><h3>Agent reasoning</h3><span className="muted">{d.agentName}</span></div><p style={{lineHeight:1.7}}>{d.reasoning}</p></div><div className="card"><div className="card-title"><h3>Risk firewall checks</h3><span className={`pill ${d.riskVerdict}`}>{d.riskVerdict}</span></div><p className="muted">{d.verdictExplanation}</p>{d.riskChecks.map(c=><div className="check" key={c.name}><span className={`check-mark ${c.status}`}>{c.status}</span><div><b>{c.name} {c.score?`+${c.score}`:""}</b><p>{c.explanation}</p></div></div>)}</div><div className="card"><div className="card-title"><h3>Raw event</h3><span className="muted">Developer view</span></div><div className="code">{JSON.stringify(d,null,2)}</div></div></div>
  <aside className="stack"><div className="card"><div className="card-title"><h3>Execution outcome</h3><span className="status">{d.executionMode}</span></div>{[["Status",d.tradeStatus],["Entry",money(d.entryPrice)],["Exit",money(d.exitPrice||d.entryPrice)],["Proposed size",(d.proposedPositionSize*100).toFixed(1)+"%"],["Final size",(d.finalPositionSize*100).toFixed(1)+"%"],["Leverage",d.leverage+"x"],["Result",money(d.resultPnL)],["Balance",money(d.balanceAfter)]].map(([a,b])=><div className="check" key={a}><span className="muted" style={{width:100}}>{a}</span><b>{b}</b></div>)}<p className="muted">{d.postTradeReview}</p></div><div className="card"><div className="card-title"><h3>Signal evidence</h3></div><div className="signals">{d.signals.map(s=><div className="signal" key={s.category}><b>{s.category.replace("_"," ")}</b><p>{s.explanation}</p><span className={s.score>.2?"positive":s.score<-.2?"negative":"muted"}>{s.score.toFixed(2)} · {s.freshness}m old</span></div>)}</div></div></aside></div></div></main>
}
